### ISSUE TITLE
There's no license

### ISSUE THREAD

**Issue by n1trux** [elsamuko/forensics#1]
As I use CC-BY-SA for my presentations and reveal.js' License seems to be compatible, why not add a good Free license?

I'd really like to translate this talk for presenting at my local hackerspace, but the license on both the talk and the pictures makes that impossible.

That said, many thanks for your forensic plugins.

**Comment by elsamuko** [comment]
Added CC licence in cb7f9c16a1a371eb99868480fa9a85594dc48c59.

This is the CC-BY licence, means only attribution is needed.
